connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://minio:9000
iceberg.rest-catalog.warehouse=s3://warehouse
iceberg.rest-catalog.s3.endpoint=http://minio:9000
iceberg.rest-catalog.s3.access-key=minioadmin
iceberg.rest-catalog.s3.secret-key=minioadmin
iceberg.rest-catalog.s3.path-style-access=true
